### ISSUE TITLE
Backend not firing any event to frontend, though in connected state

### ISSUE THREAD

**Issue by harishankards** [probil/vue-socket.io-extended#67] opened 2018-05-17 11:34 UTC
Hi,

I'm using the same code as in #65.  After solving that issue in 65, my frontend says, it's connected(identified using the console).

But, in my backend, the connect action is not working. Also, it's not listening to any function from the frontend.

What am I doing wrong? 

`Backend`
```js
io.on('connection', function(socket){
  console.log('An user connected');
  socket.on('disconnect', function(){
    console.log('user disconnected');
  });  
  
  socket.on('emit_method', function(msg){
    console.log('message: ' + msg);
  }); 
  
});
```

`Frontend`

```js
      this.$socket.emit('emit_method', 'handshake')
```

**Comment by probil** [comment] 2018-05-17 11:48
Let's check, @harishankards 
Is there any errors in browser or/and node console?

**Comment by harishankards** [comment] 2018-05-17 12:15
No errors on both side @probil.

Yes, the `An user connected` is not displayed in the backend console

**Comment by harishankards** [comment] 2018-05-17 12:29
@probil, After I start and stop the backend server every time, I get this printed to the server console everytime: 
`GET /socket.io/?EIO=3&transport=polling&t=MDk4cfm 404 25.094 ms - 149`

**Comment by probil** [comment] 2018-05-17 13:35
It's hard to guess what's wrong :thinking: . Could you please provide whole server file & client file? For example as [gist](https://gist.github.com/)?
As alternative I here is [simple echo server](https://gist.github.com/probil/907048d2cf6b4a6620aeaf2563581661) I use while testing `vue-socket.io-extended`. Basically it accepts events from the client and sends it back with the same data.

**Comment by harishankards** [comment] 2018-05-17 13:57
@probil,

I see there are a lot of variations in the backend app.js file:

**Mine:**
```js
const express = require('express');
const http = require('http');
const io = require('socket.io')(http);
```
 **Yours:**
```js
const app = require('express')();
const http = require('http').Server(app);
const io = require('socket.io')(http, { serveClient: false });
const middleware = require('socketio-wildcard')();
```

Should I replicate yours?

**Comment by probil** [comment] 2018-05-17 14:12
Hmmm. Try to replace only this line
```js
const http = require('http').Server(app);
```
There is official guide: [Using  `socket.io`  with express](https://socket.io/docs/#using-with-express-3/4)

**Comment by harishankards** [comment] 2018-05-17 14:32
@probil, Just in case, I have put out the gist here: https://gist.github.com/harishankards/82c8d103381df5c6f79af15bca8392e0

**Comment by probil** [comment] 2018-05-17 14:57
Ok, I will check and respond soon

**Comment by harishankards** [comment] 2018-05-17 15:37
Okay @probil

**Comment by probil** [comment] 2018-05-17 15:55
You code was not working out-of-the-box
So I've added missing dependencies + removed vuex/vue-router + added stub for `App` component.
Server stopped right after starting.

So I've added port listener on back-end and `emit_event` on the front-end:
_voilà_
![screen shot](https://i.imgur.com/VxXPnDT.png)

Steps:
1. Start the server
2. Open `http://localhost:8080` (vue-cli default port)

Gist is there https://gist.github.com/probil/5fd6433b0e58b8b1ebd9ee2f7a429369

**Comment by probil** [comment] 2018-05-17 15:58
Port should be the same here
```js
# BE
server.listen(3000);
# FE
Vue.use(VueSocketio, io('http://localhost:3000'))
```

**Comment by harishankards** [comment] 2018-05-17 23:06
@probil, I understand and tried out there yesterday itself.
`server.listen(3000);` Brings me an error on the backend console:

```js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Function.listen (/home/hs/Spritle/student-burger/node-backend/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/hs/Spritle/student-burger/node-backend/app.js:383:5)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

```

Also, in my frontend main.js:
I have everything same to your code except,
```js
import App from './App' //This is my root component
```

**Comment by probil** [comment] 2018-05-18 00:03
The idea behind all of this is to reuse one `http` connection on one port between `express` and `socket.io`. That's why we pass http instance and express server around:
https://gist.github.com/probil/5fd6433b0e58b8b1ebd9ee2f7a429369#file-backend-js-L3
Maybe this will be helpful https://stackoverflow.com/q/12235406/2329774

---

It's clear to me that issue is related to `socket.io` + `express` server rather than the library itself. And I'm sure it's not related to `vue-socket.io-extended`. You can try `jquery`-based example just to verify that.

I can't reproduce the issue with the latest version of the library and the code I've provide you above. So, because of that _I going to close the issue_. I don't have time to solve unrelated issues. Sorry. Try to create a question on StackOverflow instead. Post link to the question here and maybe I will try to respond.

In any case, thanks for your time, @harishankards. 
Don't hesitate if you have any other issues related to the library. I will be glad to help. Have a nice day :smile:

**Closed by probil** 2018-05-18 00:03 UTC
Labels: question

**Comment by harishankards** [comment] 2018-05-18 01:27
Hey @probil,

I completely agree with you. Will search through the socket.io and express forums. Anyway thanks for your time and help.

Really appreciate it! Have a good day, you too!

**Comment by harishankards** [comment] 2018-05-18 06:59
Hey @probil,

Fixed it myself.
The solution at backend: https://gist.github.com/harishankards/82c8d103381df5c6f79af15bca8392e0#file-backend-solution-js

**Comment by probil** [comment] 2018-05-18 10:12
Thanks great, @harishankards :tada:
